"""Independent check of tests/kinematics_fixtures.json (forward kinematics part).

The fixtures are generated by the JavaScript (tests/gen_fixtures.mjs). This script
re-computes the forward kinematics of every recorded pose in plain Python, using
only the dimensions stored in the fixture's "config" block (the same numbers as
js/arm_config.js), and compares the key points and the tool rotation. It shares
no code with js/kinematics.js, so a mistake in the JavaScript chain would show up
here. Run:  python3 tests/check_fk_fixtures.py
"""
import json
import math
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))


def mat_mul(a, b):
    return [[sum(a[i][k] * b[k][j] for k in range(4)) for j in range(4)] for i in range(4)]


def trans(x, y, z):
    return [[1, 0, 0, x], [0, 1, 0, y], [0, 0, 1, z], [0, 0, 0, 1]]


def rot(axis, deg):
    a = math.radians(deg)
    c, s = math.cos(a), math.sin(a)
    if axis == "x":
        return [[1, 0, 0, 0], [0, c, -s, 0], [0, s, c, 0], [0, 0, 0, 1]]
    if axis == "y":
        return [[c, 0, s, 0], [0, 1, 0, 0], [-s, 0, c, 0], [0, 0, 0, 1]]
    return [[c, -s, 0, 0], [s, c, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


def pos(m):
    return [m[0][3], m[1][3], m[2][3]]


def chain(cfg):
    """(offset applied before the joint, axis) - the real CTE arm, see js/arm_config.js [S7]."""
    return [
        ([0, 0, 0], "z"),
        ([cfg["SHOULDER_OFFSET"], 0, cfg["BASE_HEIGHT"]], "y"),
        ([0, 0, cfg["UPPER_ARM"]], "y"),
        ([cfg["FOREARM"], 0, cfg["ELBOW_OFFSET"]], "x"),
        ([0, 0, 0], "y"),
        ([0, 0, 0], "x"),
    ]


def forward(cfg, q, tool_length):
    t = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    frames = []
    for (off, axis), angle in zip(chain(cfg), q):
        t = mat_mul(mat_mul(t, trans(*off)), rot(axis, angle))
        frames.append(t)
    flange = mat_mul(t, trans(cfg["WRIST_TO_FLANGE"], 0, 0))
    tcp = mat_mul(flange, trans(tool_length, 0, 0))
    points = {
        "base": pos(frames[0]), "shoulder": pos(frames[1]), "elbow": pos(frames[2]),
        "forearm": pos(mat_mul(frames[2], trans(0, 0, cfg["ELBOW_OFFSET"]))),
        "wrist": pos(frames[3]), "flange": pos(flange), "tool": pos(tcp),
    }
    rotation = [row[:3] for row in tcp[:3]]
    return points, rotation


class FKFixtures(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(os.path.join(HERE, "kinematics_fixtures.json"), encoding="utf-8") as f:
            cls.fx = json.load(f)
        cls.cfg = cls.fx["config"]

    def test_config_matches_arm_config_js(self):
        """The numbers baked into the fixture must be the ones in js/arm_config.js."""
        with open(os.path.join(HERE, "..", "js", "arm_config.js"), encoding="utf-8") as f:
            src = f.read()
        import re
        for name in ["BASE_HEIGHT", "SHOULDER_OFFSET", "UPPER_ARM", "FOREARM", "ELBOW_OFFSET", "WRIST_TO_FLANGE"]:
            m = re.search(r"export const %s = ([0-9.]+)" % name, src)
            self.assertIsNotNone(m, name)
            self.assertAlmostEqual(float(m.group(1)), self.cfg[name], places=6, msg=name)

    def test_forward_kinematics(self):
        for case in self.fx["fk"]:
            points, rotation = forward(self.cfg, case["q"], case["toolLength"])
            for name, want in case["points"].items():
                got = points[name]
                for k in range(3):
                    self.assertAlmostEqual(got[k], want[k], delta=2e-3, msg="q=%s %s[%d]" % (case["q"], name, k))
            for i in range(3):
                for j in range(3):
                    self.assertAlmostEqual(rotation[i][j], case["rotation"][i][j], delta=2e-6, msg="rotation %d,%d" % (i, j))

    def test_pose_problems(self):
        """Floor and base keep-out rules, recomputed from the points."""
        cfg = self.cfg
        for case in self.fx["fk"]:
            points, _ = forward(cfg, case["q"], case["toolLength"])
            below = [n for n, p in points.items() if p[2] < -cfg["FLOOR_MARGIN"]]
            hits = [n for n in ["wrist", "flange", "tool"]
                    if any(math.hypot(points[n][0], points[n][1]) < r and points[n][2] < h for r, h in cfg["BASE_KEEPOUT"])]
            limits = any(not (lo - 1e-6 <= v <= hi + 1e-6) for v, (lo, hi) in zip(case["q"], cfg["JOINT_LIMITS"]))
            want = []
            if limits:
                want.append("joint limit exceeded")
            if below:
                want.append("below floor: " + ", ".join(below))
            if hits:
                want.append("hits base: " + ", ".join(hits))
            self.assertEqual(want, case["problems"], "q=%s" % case["q"])

    def test_lesson_geometry(self):
        """Sanity numbers from VEX's lesson: shoulder 84 mm up and 20.5 mm forward; with the
        upper arm vertical, the forearm level and the tool straight down the magnet TCP is
        about (195, 0, 192) like VEX's side-view diagram (TCP 'just under 200 mm' high)."""
        cfg = self.cfg
        points, _ = forward(cfg, [0, 0, 0, 0, 90, 0], cfg["TOOL_LENGTH"]["MAGNET"])
        self.assertAlmostEqual(points["shoulder"][2], 84.0, delta=1e-9)
        self.assertAlmostEqual(points["shoulder"][0], 20.5, delta=1e-9)
        self.assertAlmostEqual(points["elbow"][2], 84.0 + 133.0, delta=1e-9)
        self.assertAlmostEqual(points["wrist"][0], 20.5 + 174.0, delta=1e-9)
        self.assertAlmostEqual(points["wrist"][2], 84.0 + 133.0 + 28.0, delta=1e-9)
        self.assertAlmostEqual(points["tool"][0], 194.5, delta=0.01)
        self.assertAlmostEqual(points["tool"][2], 245.0 - 13.0 - 38.5, delta=0.01)


if __name__ == "__main__":
    sys.exit(unittest.main(verbosity=2))
