// gen_fixtures.mjs - (re)generate tests/kinematics_fixtures.json.
//
// History: the first fixtures were produced by the Python v4 simulator, whose
// arm dimensions were estimates (base 95 mm, two 167.5 mm links, no offsets).
// When the geometry was corrected to the real VEX CTE arm (see js/arm_config.js
// [S7]) those numbers stopped being meaningful, so the fixtures are now produced
// here, from the JavaScript, as a REGRESSION snapshot:
//   * fk        forward kinematics points / rotation / pose problems / self hits for
//               30 pseudo-random poses (seeded) and the 3 tools. These are checked
//               independently by tests/check_fk_fixtures.py (a separate Python FK
//               that only shares the constants), so a wrong chain cannot hide here.
//   * ik, plan, reach   IK answers, a straight-line plan and the reach-map radial
//               profiles - these pin down the solver's behaviour between changes.
// Run:  node tests/gen_fixtures.mjs        (then review the diff and commit it)
import fs from "node:fs";
import * as cfg from "../js/arm_config.js";
import * as kin from "../js/kinematics.js";
import * as col from "../js/collision.js";
import { radialProfileSync } from "../js/reach_map.js";

const r6 = (v) => Math.round(v * 1e6) / 1e6;
const round = (x) => (Array.isArray(x) ? x.map(round) : typeof x === "number" ? r6(x) : x);

// mulberry32: tiny seeded PRNG so the poses are reproducible
function rng(seed) { return () => { seed |= 0; seed = (seed + 0x6D2B79F5) | 0; let t = Math.imul(seed ^ (seed >>> 15), 1 | seed); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
const rand = rng(1234);
const tools = [["MAGNET", cfg.TOOL_LENGTH.MAGNET], ["PEN", cfg.TOOL_LENGTH.PEN], ["NONE", 0]];

const fk = [];
for (let i = 0; i < 30; i++) {
  const q = cfg.JOINT_LIMITS.map(([lo, hi]) => r6(lo + (hi - lo) * rand()));
  const [tool, toolLength] = tools[i % 3];
  const f = kin.forwardKinematics(q, toolLength);
  fk.push({ q, tool, toolLength, points: round(f.points()), rotation: round(f.rotation), problems: kin.poseProblems(q, toolLength),
    selfHits: col.armSelfHits(f, tool).map((h) => [...h]).sort() });
}

const targets = [[120, 0, 100], [200, 50, 55], [175, 115, 45], [112, 112, 45], [160, -90, 25], [250, 0, 20], [90, 180, 10], [300, 0, 0], [60, 0, 0],
  [0, 0, 400], [380, 0, 50], [500, 0, 50], [150, 0, -5], [220, -150, 80], [140, 110, 8], [200, 200, 0], [330, 0, 60]];
const ik = [];
for (const target of targets) for (const mode of ["down", "free"]) {
  const r = kin.solveIK(target, { toolDir: mode === "down" ? kin.DOWN : null });
  ik.push({ target, mode, success: r.success, q: round(r.q), positionError: r6(r.positionError), reason: r.reason });
}

const start = kin.solveIK([120, 0, 100], { toolDir: kin.DOWN });
const keys = kin.planLinear(start.q, [200, 60, 40], null, kin.DOWN);
const plan = { qStart: round(start.q), target: [200, 60, 40], keys: round(keys) };

const reach = {};
for (const z of [0, 50, 100]) { const p = radialProfileSync(z, cfg.TOOL_LENGTH.MAGNET); reach[z.toFixed(1)] = { radii: p.radii, ok: p.ok }; }

const out = { about: "Generated by tests/gen_fixtures.mjs - see the comment there. Regenerate when js/arm_config.js changes.",
  config: { BASE_HEIGHT: cfg.BASE_HEIGHT, SHOULDER_OFFSET: cfg.SHOULDER_OFFSET, UPPER_ARM: cfg.UPPER_ARM, FOREARM: cfg.FOREARM, ELBOW_OFFSET: cfg.ELBOW_OFFSET,
    WRIST_TO_FLANGE: cfg.WRIST_TO_FLANGE, TOOL_LENGTH: cfg.TOOL_LENGTH, JOINT_LIMITS: cfg.JOINT_LIMITS, BASE_KEEPOUT: cfg.BASE_KEEPOUT, FLOOR_MARGIN: cfg.FLOOR_MARGIN },
  fk, ik, plan, reach };
const path = new URL("./kinematics_fixtures.json", import.meta.url);
fs.writeFileSync(path, JSON.stringify(out));
console.log(`wrote ${path.pathname}: ${fk.length} fk, ${ik.length} ik (${ik.filter((c) => c.success).length} reachable), plan ${keys ? keys.length : 0} keys, reach z=${Object.keys(reach).join(",")}`);
